import { z } from 'zod';

export const schemas = {
  move: z.object({ x: z.number(), z: z.number(), rotY: z.number() }),
  chat: z.object({ text: z.string().min(1).max(500) }),
  whisper: z.object({ to: z.string(), text: z.string().min(1).max(200) }),
  target: z.object({ targetId: z.string().optional() }),
  attack: z.object({ targetId: z.string() }),
  cast_skill: z.object({ skillId: z.string(), targetId: z.string().optional() }),
  useItem: z.object({ invIndex: z.number().int() }),
  equip: z.object({ slotIndex: z.number().int() }),
  unequip: z.object({ slot: z.enum(['weapon', 'armor']) }),
  craft: z.object({ recipeId: z.string(), benchTier: z.number().int().default(0), count: z.number().int().positive().default(1) }),
  harvest: z.object({ plantId: z.string() }),
  plant: z.object({ itemId: z.string(), x: z.number(), z: z.number() }),
  respawn: z.object({}),
  logout: z.object({}),
  warp: z.object({ mapId: z.string() }),
  accept_proposal: z.object({ proposerName: z.string() }),
  decline_proposal: z.object({ proposerName: z.string() }),
  trade_request: z.object({ playerId: z.string() }),
  trade_accept: z.object({ playerId: z.string() }),
  trade_cancel: z.object({}),
  buy_npc: z.object({ npcId: z.string(), itemId: z.string(), qty: z.number().int().positive().default(1) }),
  sell_npc: z.object({ slotIndex: z.number().int(), qty: z.number().int().positive().default(1) }),
  waypoint_set: z.object({ label: z.string().optional() }),
  companion_release: z.object({ companionId: z.string() }),
  accept_party: z.object({ partyId: z.string() }),
  decline_party: z.object({ partyId: z.string() }),
  leave_party: z.object({}),
  disband_party: z.object({}),
  auction_list: z.object({ itemId: z.string(), startingPrice: z.number().positive(), duration: z.enum(['1h','4h','12h','24h']).default('4h') }),
  auction_bid: z.object({ auctionId: z.string(), amount: z.number().positive() }),
  auction_cancel: z.object({ auctionId: z.string() }),
  enchant: z.object({ slotIndex: z.number().int() }),
  repair: z.object({ slotIndex: z.number().int() }),
  guild_create: z.object({ name: z.string().min(3).max(24) }),
  guild_disband: z.object({}),
  guild_invite: z.object({ playerName: z.string() }),
  guild_leave: z.object({}),
  guild_kick: z.object({ memberName: z.string() }),
};

export type Schemas = typeof schemas;